project_id = "edtudwkmswyjxamkdkbu"

[functions.fetch-prices]
verify_jwt = false

[functions.search-ticker]
verify_jwt = false

[functions.create-monthly-snapshot]
verify_jwt = false

[functions.fetch-crypto-prices]
verify_jwt = false

[functions.financial-advisor]
verify_jwt = false
