#!/usr/bin/env bash
# ===========================================================================
# load-secrets.sh — Pulls secrets from macOS Keychain into a temporary .env
# file for CRE CLI consumption. The .env is written with chmod 600.
#
# Usage:
#   source load-secrets.sh          # exports ENV_FILE for use with CRE
#   cre workflow simulate ... -e "$ENV_FILE"
#
# Or as a one-liner:
#   eval "$(./load-secrets.sh --export)"
# ===========================================================================
set -euo pipefail

ACCOUNT="incontrol"
ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env"

fetch() {
  security find-generic-password -a "$ACCOUNT" -s "$1" -w 2>/dev/null
}

echo "🔑 Loading secrets from macOS Keychain (account: $ACCOUNT)..."

SUPABASE_ANON_KEY=$(fetch SUPABASE_ANON_KEY)
CRE_ETH_PRIVATE_KEY=$(fetch CRE_ETH_PRIVATE_KEY)
SUPABASE_SERVICE_ROLE_KEY=$(fetch SUPABASE_SERVICE_ROLE_KEY)
CRON_SECRET=$(fetch CRON_SECRET)

# Write to .env with strict permissions
cat > "$ENV_FILE" <<EOF
###############################################################################
### AUTO-GENERATED by load-secrets.sh — DO NOT EDIT MANUALLY               ###
### Secrets are pulled from macOS Keychain (account: $ACCOUNT)             ###
###############################################################################
SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
CRE_ETH_PRIVATE_KEY=$CRE_ETH_PRIVATE_KEY
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
CRON_SECRET=$CRON_SECRET
EOF

chmod 600 "$ENV_FILE"

echo "✅ .env written to $ENV_FILE (chmod 600)"
echo "   Use: cre workflow simulate ... -e \"$ENV_FILE\""

# Export for convenience if sourced
export ENV_FILE
